### ISSUE TITLE
This is what i do for fun

### ISSUE THREAD

**Issue by RachelScodes** [RachelScodes/HowManyQuestions#1]
I wrote an app... to help me write my app. Yes. I know. It's slow, but it gets the job done.

Anyone have a clue why it randomly gives me 304s instead of 200?

Hope you guys have a happy thanksgiving. eat lots of turkey (or tofurkey if that's your thing), and take lots of naps.

**Comment by RachelScodes** [comment]
...i changed nothing and it all works now. ::shrug::

**Comment by sssyed** [comment]
hm my only guess is that you're hitting a limiting on the endpoint you're trying to ping? you might have only a certain amount requests you can make per second.

**Comment by RachelScodes** [comment]
it was so weird. i closed the laptop and came back to it later and it was all 200s all the time. it must have been a limit on their end.

**Comment by sssyed** [comment]
yeah most open apis do!
